/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  AuthenticateRequestBody,
  AuthenticateResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    AuthenticateRequestBodyFromJSON,
    AuthenticateRequestBodyToJSON,
    AuthenticateResponseFromJSON,
    AuthenticateResponseToJSON,
} from '../models/index';

export interface AuthenticateRequest {
    authenticateRequestBody: AuthenticateRequestBody;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Get the access token, needed for all other API requests.  You will need your client ID and secret from the **API Integration** tab of the Vouchsafe dashboard.  Each access token is valid for 24 hours, after which you will need to re-authenticate.  Once you have an access token, pass it in future requests as a [Bearer token](https://workos.com/blog/understanding-bearer-tokens) in an `Authorization` header.  > This endpoint supports sandbox mode. [See how sandbox mode works](https://help.vouchsafe.id/en/articles/11979598-how-does-sandbox-mode-work).
     */
    async authenticateRaw(requestParameters: AuthenticateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthenticateResponse>> {
        if (requestParameters['authenticateRequestBody'] == null) {
            throw new runtime.RequiredError(
                'authenticateRequestBody',
                'Required parameter "authenticateRequestBody" was null or undefined when calling authenticate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/authenticate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthenticateRequestBodyToJSON(requestParameters['authenticateRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthenticateResponseFromJSON(jsonValue));
    }

    /**
     * Get the access token, needed for all other API requests.  You will need your client ID and secret from the **API Integration** tab of the Vouchsafe dashboard.  Each access token is valid for 24 hours, after which you will need to re-authenticate.  Once you have an access token, pass it in future requests as a [Bearer token](https://workos.com/blog/understanding-bearer-tokens) in an `Authorization` header.  > This endpoint supports sandbox mode. [See how sandbox mode works](https://help.vouchsafe.id/en/articles/11979598-how-does-sandbox-mode-work).
     */
    async authenticate(requestParameters: AuthenticateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthenticateResponse> {
        const response = await this.authenticateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
