/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticateResponse
 */
export interface AuthenticateResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthenticateResponse
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticateResponse
     */
    expiresAt: string;
}

/**
 * Check if a given object implements the AuthenticateResponse interface.
 */
export function instanceOfAuthenticateResponse(value: object): value is AuthenticateResponse {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function AuthenticateResponseFromJSON(json: any): AuthenticateResponse {
    return AuthenticateResponseFromJSONTyped(json, false);
}

export function AuthenticateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'expiresAt': json['expires_at'],
    };
}

export function AuthenticateResponseToJSON(json: any): AuthenticateResponse {
    return AuthenticateResponseToJSONTyped(json, false);
}

export function AuthenticateResponseToJSONTyped(value?: AuthenticateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'expires_at': value['expiresAt'],
    };
}

