/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticateInput
 */
export interface AuthenticateInput {
    /**
     * 
     * @type {string}
     * @memberof AuthenticateInput
     */
    client_id: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticateInput
     */
    client_secret: string;
}

/**
 * Check if a given object implements the AuthenticateInput interface.
 */
export function instanceOfAuthenticateInput(value: object): value is AuthenticateInput {
    if (!('client_id' in value) || value['client_id'] === undefined) return false;
    if (!('client_secret' in value) || value['client_secret'] === undefined) return false;
    return true;
}

export function AuthenticateInputFromJSON(json: any): AuthenticateInput {
    return AuthenticateInputFromJSONTyped(json, false);
}

export function AuthenticateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'client_id': json['client_id'],
        'client_secret': json['client_secret'],
    };
}

export function AuthenticateInputToJSON(json: any): AuthenticateInput {
    return AuthenticateInputToJSONTyped(json, false);
}

export function AuthenticateInputToJSONTyped(value?: AuthenticateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['client_id'],
        'client_secret': value['client_secret'],
    };
}

