/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Model36EnumsEnvironment } from './Model36EnumsEnvironment';
import {
    Model36EnumsEnvironmentFromJSON,
    Model36EnumsEnvironmentFromJSONTyped,
    Model36EnumsEnvironmentToJSON,
    Model36EnumsEnvironmentToJSONTyped,
} from './Model36EnumsEnvironment';

/**
 * Production API credentials for this team
 * @export
 * @interface CreateTeamResponseCredentials
 */
export interface CreateTeamResponseCredentials {
    /**
     * Client secret for API authentication
     * @type {string}
     * @memberof CreateTeamResponseCredentials
     */
    client_secret: string;
    /**
     * Client ID for API authentication
     * @type {string}
     * @memberof CreateTeamResponseCredentials
     */
    client_id: string;
    /**
     * 
     * @type {Model36EnumsEnvironment}
     * @memberof CreateTeamResponseCredentials
     */
    environment: Model36EnumsEnvironment;
    /**
     * Name of the API key
     * @type {string}
     * @memberof CreateTeamResponseCredentials
     */
    name: string;
}



/**
 * Check if a given object implements the CreateTeamResponseCredentials interface.
 */
export function instanceOfCreateTeamResponseCredentials(value: object): value is CreateTeamResponseCredentials {
    if (!('client_secret' in value) || value['client_secret'] === undefined) return false;
    if (!('client_id' in value) || value['client_id'] === undefined) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateTeamResponseCredentialsFromJSON(json: any): CreateTeamResponseCredentials {
    return CreateTeamResponseCredentialsFromJSONTyped(json, false);
}

export function CreateTeamResponseCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTeamResponseCredentials {
    if (json == null) {
        return json;
    }
    return {
        
        'client_secret': json['client_secret'],
        'client_id': json['client_id'],
        'environment': Model36EnumsEnvironmentFromJSON(json['environment']),
        'name': json['name'],
    };
}

export function CreateTeamResponseCredentialsToJSON(json: any): CreateTeamResponseCredentials {
    return CreateTeamResponseCredentialsToJSONTyped(json, false);
}

export function CreateTeamResponseCredentialsToJSONTyped(value?: CreateTeamResponseCredentials | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_secret': value['client_secret'],
        'client_id': value['client_id'],
        'environment': Model36EnumsEnvironmentToJSON(value['environment']),
        'name': value['name'],
    };
}

