/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateTeamResponseCredentials } from './CreateTeamResponseCredentials';
import {
    CreateTeamResponseCredentialsFromJSON,
    CreateTeamResponseCredentialsFromJSONTyped,
    CreateTeamResponseCredentialsToJSON,
    CreateTeamResponseCredentialsToJSONTyped,
} from './CreateTeamResponseCredentials';

/**
 * Response from creating a new team
 * @export
 * @interface CreateTeamResponse
 */
export interface CreateTeamResponse {
    /**
     * Unique identifier for the created team
     * @type {string}
     * @memberof CreateTeamResponse
     */
    id: string;
    /**
     * The name of the team.
     * @type {string}
     * @memberof CreateTeamResponse
     */
    name: string;
    /**
     * The public name of the team, shown in end-user facing screens and communications. If set, overrides the name.
     * @type {string}
     * @memberof CreateTeamResponse
     */
    public_name?: string;
    /**
     * ISO 8601 timestamp of team creation
     * @type {string}
     * @memberof CreateTeamResponse
     */
    created_at: string;
    /**
     * 
     * @type {CreateTeamResponseCredentials}
     * @memberof CreateTeamResponse
     */
    credentials: CreateTeamResponseCredentials;
}

/**
 * Check if a given object implements the CreateTeamResponse interface.
 */
export function instanceOfCreateTeamResponse(value: object): value is CreateTeamResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('credentials' in value) || value['credentials'] === undefined) return false;
    return true;
}

export function CreateTeamResponseFromJSON(json: any): CreateTeamResponse {
    return CreateTeamResponseFromJSONTyped(json, false);
}

export function CreateTeamResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTeamResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'public_name': json['public_name'] == null ? undefined : json['public_name'],
        'created_at': json['created_at'],
        'credentials': CreateTeamResponseCredentialsFromJSON(json['credentials']),
    };
}

export function CreateTeamResponseToJSON(json: any): CreateTeamResponse {
    return CreateTeamResponseToJSONTyped(json, false);
}

export function CreateTeamResponseToJSONTyped(value?: CreateTeamResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'public_name': value['public_name'],
        'created_at': value['created_at'],
        'credentials': CreateTeamResponseCredentialsToJSON(value['credentials']),
    };
}

