/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FlowTemplate = {
    KycAml: 'KYC_AML',
    RightToWork: 'RIGHT_TO_WORK',
    RightToRent: 'RIGHT_TO_RENT',
    DbsCheck: 'DBS_CHECK'
} as const;
export type FlowTemplate = typeof FlowTemplate[keyof typeof FlowTemplate];


export function instanceOfFlowTemplate(value: any): boolean {
    for (const key in FlowTemplate) {
        if (Object.prototype.hasOwnProperty.call(FlowTemplate, key)) {
            if (FlowTemplate[key as keyof typeof FlowTemplate] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FlowTemplateFromJSON(json: any): FlowTemplate {
    return FlowTemplateFromJSONTyped(json, false);
}

export function FlowTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlowTemplate {
    return json as FlowTemplate;
}

export function FlowTemplateToJSON(value?: FlowTemplate | null): any {
    return value as any;
}

export function FlowTemplateToJSONTyped(value: any, ignoreDiscriminator: boolean): FlowTemplate {
    return value as FlowTemplate;
}

