/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Report } from './Report';
import {
    ReportFromJSON,
    ReportFromJSONTyped,
    ReportToJSON,
    ReportToJSONTyped,
} from './Report';
import type { Model36EnumsBackgroundCheck } from './Model36EnumsBackgroundCheck';
import {
    Model36EnumsBackgroundCheckFromJSON,
    Model36EnumsBackgroundCheckFromJSONTyped,
    Model36EnumsBackgroundCheckToJSON,
    Model36EnumsBackgroundCheckToJSONTyped,
} from './Model36EnumsBackgroundCheck';

/**
 * 
 * @export
 * @interface GetSmartLookupResponse
 */
export interface GetSmartLookupResponse {
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    teamId: string;
    /**
     * 
     * @type {Array<Model36EnumsBackgroundCheck>}
     * @memberof GetSmartLookupResponse
     */
    checks: Array<Model36EnumsBackgroundCheck>;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    firstName: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    lastName: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    firstLineOfAddress: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    postcode: string | null;
    /**
     * Whether the overall check and its sub-checks passed, failed or somethng else.
     * @type {Report}
     * @memberof GetSmartLookupResponse
     */
    addressVerificationReport: Report | null;
    /**
     * Extra information to aid debugging. May change without notice.
     * @type {any}
     * @memberof GetSmartLookupResponse
     */
    metadata: any | null;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    createdAt: string;
}

/**
 * Check if a given object implements the GetSmartLookupResponse interface.
 */
export function instanceOfGetSmartLookupResponse(value: object): value is GetSmartLookupResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    if (!('checks' in value) || value['checks'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('firstLineOfAddress' in value) || value['firstLineOfAddress'] === undefined) return false;
    if (!('postcode' in value) || value['postcode'] === undefined) return false;
    if (!('addressVerificationReport' in value) || value['addressVerificationReport'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function GetSmartLookupResponseFromJSON(json: any): GetSmartLookupResponse {
    return GetSmartLookupResponseFromJSONTyped(json, false);
}

export function GetSmartLookupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSmartLookupResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'teamId': json['team_id'],
        'checks': ((json['checks'] as Array<any>).map(Model36EnumsBackgroundCheckFromJSON)),
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'firstLineOfAddress': json['first_line_of_address'],
        'postcode': json['postcode'],
        'addressVerificationReport': ReportFromJSON(json['address_verification_report']),
        'metadata': json['metadata'],
        'createdAt': json['created_at'],
    };
}

export function GetSmartLookupResponseToJSON(json: any): GetSmartLookupResponse {
    return GetSmartLookupResponseToJSONTyped(json, false);
}

export function GetSmartLookupResponseToJSONTyped(value?: GetSmartLookupResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'team_id': value['teamId'],
        'checks': ((value['checks'] as Array<any>).map(Model36EnumsBackgroundCheckToJSON)),
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'first_line_of_address': value['firstLineOfAddress'],
        'postcode': value['postcode'],
        'address_verification_report': ReportToJSON(value['addressVerificationReport']),
        'metadata': value['metadata'],
        'created_at': value['createdAt'],
    };
}

