/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Report } from './Report';
import {
    ReportFromJSON,
    ReportFromJSONTyped,
    ReportToJSON,
    ReportToJSONTyped,
} from './Report';
import type { Model36EnumsBackgroundCheck } from './Model36EnumsBackgroundCheck';
import {
    Model36EnumsBackgroundCheckFromJSON,
    Model36EnumsBackgroundCheckFromJSONTyped,
    Model36EnumsBackgroundCheckToJSON,
    Model36EnumsBackgroundCheckToJSONTyped,
} from './Model36EnumsBackgroundCheck';

/**
 * 
 * @export
 * @interface GetSmartLookupResponse
 */
export interface GetSmartLookupResponse {
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    team_id: string;
    /**
     * 
     * @type {Array<Model36EnumsBackgroundCheck>}
     * @memberof GetSmartLookupResponse
     */
    checks: Array<Model36EnumsBackgroundCheck>;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    first_name: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    last_name: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    first_line_of_address: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    postcode: string | null;
    /**
     * Whether the overall check and its sub-checks passed, failed or somethng else.
     * @type {Report}
     * @memberof GetSmartLookupResponse
     */
    address_verification_report: Report | null;
    /**
     * Extra information to aid debugging. May change without notice.
     * @type {any}
     * @memberof GetSmartLookupResponse
     */
    metadata: any | null;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    created_at: string;
}

/**
 * Check if a given object implements the GetSmartLookupResponse interface.
 */
export function instanceOfGetSmartLookupResponse(value: object): value is GetSmartLookupResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('team_id' in value) || value['team_id'] === undefined) return false;
    if (!('checks' in value) || value['checks'] === undefined) return false;
    if (!('first_name' in value) || value['first_name'] === undefined) return false;
    if (!('last_name' in value) || value['last_name'] === undefined) return false;
    if (!('first_line_of_address' in value) || value['first_line_of_address'] === undefined) return false;
    if (!('postcode' in value) || value['postcode'] === undefined) return false;
    if (!('address_verification_report' in value) || value['address_verification_report'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function GetSmartLookupResponseFromJSON(json: any): GetSmartLookupResponse {
    return GetSmartLookupResponseFromJSONTyped(json, false);
}

export function GetSmartLookupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSmartLookupResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'team_id': json['team_id'],
        'checks': ((json['checks'] as Array<any>).map(Model36EnumsBackgroundCheckFromJSON)),
        'first_name': json['first_name'],
        'last_name': json['last_name'],
        'first_line_of_address': json['first_line_of_address'],
        'postcode': json['postcode'],
        'address_verification_report': ReportFromJSON(json['address_verification_report']),
        'metadata': json['metadata'],
        'created_at': json['created_at'],
    };
}

export function GetSmartLookupResponseToJSON(json: any): GetSmartLookupResponse {
    return GetSmartLookupResponseToJSONTyped(json, false);
}

export function GetSmartLookupResponseToJSONTyped(value?: GetSmartLookupResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'team_id': value['team_id'],
        'checks': ((value['checks'] as Array<any>).map(Model36EnumsBackgroundCheckToJSON)),
        'first_name': value['first_name'],
        'last_name': value['last_name'],
        'first_line_of_address': value['first_line_of_address'],
        'postcode': value['postcode'],
        'address_verification_report': ReportToJSON(value['address_verification_report']),
        'metadata': value['metadata'],
        'created_at': value['created_at'],
    };
}

