/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Model36EnumsBackgroundCheck = {
    Aml: 'AML',
    Address: 'Address',
    OnlineFootprint: 'OnlineFootprint',
    DataBreaches: 'DataBreaches'
} as const;
export type Model36EnumsBackgroundCheck = typeof Model36EnumsBackgroundCheck[keyof typeof Model36EnumsBackgroundCheck];


export function instanceOfModel36EnumsBackgroundCheck(value: any): boolean {
    for (const key in Model36EnumsBackgroundCheck) {
        if (Object.prototype.hasOwnProperty.call(Model36EnumsBackgroundCheck, key)) {
            if (Model36EnumsBackgroundCheck[key as keyof typeof Model36EnumsBackgroundCheck] === value) {
                return true;
            }
        }
    }
    return false;
}

export function Model36EnumsBackgroundCheckFromJSON(json: any): Model36EnumsBackgroundCheck {
    return Model36EnumsBackgroundCheckFromJSONTyped(json, false);
}

export function Model36EnumsBackgroundCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model36EnumsBackgroundCheck {
    return json as Model36EnumsBackgroundCheck;
}

export function Model36EnumsBackgroundCheckToJSON(value?: Model36EnumsBackgroundCheck | null): any {
    return value as any;
}

export function Model36EnumsBackgroundCheckToJSONTyped(value: any, ignoreDiscriminator: boolean): Model36EnumsBackgroundCheck {
    return value as Model36EnumsBackgroundCheck;
}

