/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Model36EnumsEnvironment = {
    Production: 'production',
    Sandbox: 'sandbox'
} as const;
export type Model36EnumsEnvironment = typeof Model36EnumsEnvironment[keyof typeof Model36EnumsEnvironment];


export function instanceOfModel36EnumsEnvironment(value: any): boolean {
    for (const key in Model36EnumsEnvironment) {
        if (Object.prototype.hasOwnProperty.call(Model36EnumsEnvironment, key)) {
            if (Model36EnumsEnvironment[key as keyof typeof Model36EnumsEnvironment] === value) {
                return true;
            }
        }
    }
    return false;
}

export function Model36EnumsEnvironmentFromJSON(json: any): Model36EnumsEnvironment {
    return Model36EnumsEnvironmentFromJSONTyped(json, false);
}

export function Model36EnumsEnvironmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model36EnumsEnvironment {
    return json as Model36EnumsEnvironment;
}

export function Model36EnumsEnvironmentToJSON(value?: Model36EnumsEnvironment | null): any {
    return value as any;
}

export function Model36EnumsEnvironmentToJSONTyped(value: any, ignoreDiscriminator: boolean): Model36EnumsEnvironment {
    return value as Model36EnumsEnvironment;
}

