/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostcodeResponse
 */
export interface PostcodeResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof PostcodeResponse
     */
    addresses: Array<string>;
}

/**
 * Check if a given object implements the PostcodeResponse interface.
 */
export function instanceOfPostcodeResponse(value: object): value is PostcodeResponse {
    if (!('addresses' in value) || value['addresses'] === undefined) return false;
    return true;
}

export function PostcodeResponseFromJSON(json: any): PostcodeResponse {
    return PostcodeResponseFromJSONTyped(json, false);
}

export function PostcodeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostcodeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'addresses': json['addresses'],
    };
}

export function PostcodeResponseToJSON(json: any): PostcodeResponse {
    return PostcodeResponseToJSONTyped(json, false);
}

export function PostcodeResponseToJSONTyped(value?: PostcodeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addresses': value['addresses'],
    };
}

