/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckResult } from './CheckResult';
import {
    CheckResultFromJSON,
    CheckResultFromJSONTyped,
    CheckResultToJSON,
    CheckResultToJSONTyped,
} from './CheckResult';

/**
 * Construct a type with a set of properties K of type T
 * @export
 * @interface RecordAddressVerificationChecksCheckResult
 */
export interface RecordAddressVerificationChecksCheckResult {
    /**
     * 
     * @type {CheckResult}
     * @memberof RecordAddressVerificationChecksCheckResult
     */
    POSTCODE_EXISTS: CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof RecordAddressVerificationChecksCheckResult
     */
    ADDRESS_EXISTS: CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof RecordAddressVerificationChecksCheckResult
     */
    PERSON_LIVES_AT_ADDRESS: CheckResult;
}

/**
 * Check if a given object implements the RecordAddressVerificationChecksCheckResult interface.
 */
export function instanceOfRecordAddressVerificationChecksCheckResult(value: object): value is RecordAddressVerificationChecksCheckResult {
    if (!('POSTCODE_EXISTS' in value) || value['POSTCODE_EXISTS'] === undefined) return false;
    if (!('ADDRESS_EXISTS' in value) || value['ADDRESS_EXISTS'] === undefined) return false;
    if (!('PERSON_LIVES_AT_ADDRESS' in value) || value['PERSON_LIVES_AT_ADDRESS'] === undefined) return false;
    return true;
}

export function RecordAddressVerificationChecksCheckResultFromJSON(json: any): RecordAddressVerificationChecksCheckResult {
    return RecordAddressVerificationChecksCheckResultFromJSONTyped(json, false);
}

export function RecordAddressVerificationChecksCheckResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordAddressVerificationChecksCheckResult {
    if (json == null) {
        return json;
    }
    return {
        
        'POSTCODE_EXISTS': CheckResultFromJSON(json['POSTCODE_EXISTS']),
        'ADDRESS_EXISTS': CheckResultFromJSON(json['ADDRESS_EXISTS']),
        'PERSON_LIVES_AT_ADDRESS': CheckResultFromJSON(json['PERSON_LIVES_AT_ADDRESS']),
    };
}

export function RecordAddressVerificationChecksCheckResultToJSON(json: any): RecordAddressVerificationChecksCheckResult {
    return RecordAddressVerificationChecksCheckResultToJSONTyped(json, false);
}

export function RecordAddressVerificationChecksCheckResultToJSONTyped(value?: RecordAddressVerificationChecksCheckResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'POSTCODE_EXISTS': CheckResultToJSON(value['POSTCODE_EXISTS']),
        'ADDRESS_EXISTS': CheckResultToJSON(value['ADDRESS_EXISTS']),
        'PERSON_LIVES_AT_ADDRESS': CheckResultToJSON(value['PERSON_LIVES_AT_ADDRESS']),
    };
}

