/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecordAddressVerificationChecksCheckResult } from './RecordAddressVerificationChecksCheckResult';
import {
    RecordAddressVerificationChecksCheckResultFromJSON,
    RecordAddressVerificationChecksCheckResultFromJSONTyped,
    RecordAddressVerificationChecksCheckResultToJSON,
    RecordAddressVerificationChecksCheckResultToJSONTyped,
} from './RecordAddressVerificationChecksCheckResult';
import type { CheckState } from './CheckState';
import {
    CheckStateFromJSON,
    CheckStateFromJSONTyped,
    CheckStateToJSON,
    CheckStateToJSONTyped,
} from './CheckState';

/**
 * 
 * @export
 * @interface Report
 */
export interface Report {
    /**
     * 
     * @type {CheckState}
     * @memberof Report
     */
    state: CheckState;
    /**
     * 
     * @type {RecordAddressVerificationChecksCheckResult}
     * @memberof Report
     */
    checks: RecordAddressVerificationChecksCheckResult;
}



/**
 * Check if a given object implements the Report interface.
 */
export function instanceOfReport(value: object): value is Report {
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('checks' in value) || value['checks'] === undefined) return false;
    return true;
}

export function ReportFromJSON(json: any): Report {
    return ReportFromJSONTyped(json, false);
}

export function ReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): Report {
    if (json == null) {
        return json;
    }
    return {
        
        'state': CheckStateFromJSON(json['state']),
        'checks': RecordAddressVerificationChecksCheckResultFromJSON(json['checks']),
    };
}

export function ReportToJSON(json: any): Report {
    return ReportToJSONTyped(json, false);
}

export function ReportToJSONTyped(value?: Report | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state': CheckStateToJSON(value['state']),
        'checks': RecordAddressVerificationChecksCheckResultToJSON(value['checks']),
    };
}

